/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.ufsm;

import org.junit.jupiter.api.Test;
import org.ufsm.App;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
	User usuario = new User("Teste", 20, 170);
	
    @Test
    void testUserName() {
    	assertNotEquals(usuario, new User("Teste", 20, 170));
    }
}
