/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import java.util.HashMap;

public class ConversorNumeros {
	private static HashMap<Character, Integer> tabela = new HashMap<Character, Integer>(){{
		put('I', 1);
		put('V', 5);
		put('X', 10);
		put('L', 50);
		put('C', 100);
		put('D', 500);
		put('M', 1000);
	}};
    public static int converteRtoI(String num_romano) {
    	num_romano = num_romano.toUpperCase();
    	int acum = 0;
    	int ultimo_viz_dir = 0;
    	for(int i = num_romano.length() - 1; i >= 0; i--) {
    		int atual = tabela.get(num_romano.charAt(i));
    		int mult = 1;
    		if(atual < ultimo_viz_dir) {
    			mult = -1;
    		}
    		acum += tabela.get(num_romano.charAt(i))*mult;
    		
    		ultimo_viz_dir = atual;
    		
    	}
    	return acum;
    }
}
