/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

public class ConversorNumeros {
    public static int converteRtoI(String num_romano) {
    	num_romano.toLowerCase();
    	return 0;
    }
}
